services:
  api:
    platform: linux/arm64/v8
    image: mcthoughtworks/device-control:latest
    container_name: api
    restart: on-failure
    depends_on:
      - postgres_dc
    ports:
      - "8080:8080"
    environment:
      - DC_DATASOURCE_URL=jdbc:postgresql://postgres_dc:5432/devices-db
    volumes:
      - .:/core
    networks:
      - dc

  postgres_dc:
    image: postgres
    container_name: postgres_dc
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devices-db
    volumes:
      - .docker/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - dc

networks:
  dc:
    driver: bridge